// <auto-generated />
using System;
using BackendLicenta.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendLicenta.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20220416171339_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BackendLicenta.Context.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Game2048Score")
                        .HasColumnType("int");

                    b.Property<int>("MinesweeperScoreEasy")
                        .HasColumnType("int");

                    b.Property<int>("MinesweeperScoreHard")
                        .HasColumnType("int");

                    b.Property<int>("MinesweeperScoreMedium")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordleScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7bf5314-3dda-4290-9cfc-cd0d508bfa40"),
                            Game2048Score = 1,
                            MinesweeperScoreEasy = 1,
                            MinesweeperScoreHard = 5,
                            MinesweeperScoreMedium = 3,
                            Username = "Alex",
                            WordleScore = 1
                        },
                        new
                        {
                            Id = new Guid("b3b79140-7fed-4f0b-b09f-1140e157b147"),
                            Game2048Score = 24,
                            MinesweeperScoreEasy = 3,
                            MinesweeperScoreHard = 5,
                            MinesweeperScoreMedium = 5,
                            Username = "Andrei",
                            WordleScore = 56
                        },
                        new
                        {
                            Id = new Guid("98479990-8d91-4fc0-8b80-43d53bf28c72"),
                            Game2048Score = 25,
                            MinesweeperScoreEasy = 3,
                            MinesweeperScoreHard = 2,
                            MinesweeperScoreMedium = 7,
                            Username = "John",
                            WordleScore = 25
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
